name: Deploy to IONOS

on:
  push:
    branches:
      - main  # o master, según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 📂 SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22  # Puerto SFTP estándar
          protocol: sftp
          server-dir: /  # O la ruta específica en tu hosting
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .env
            .env.example 