name: Deploy to Hosting

on:
  push:
    branches:
      - main  # Puedes cambiar esto a la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Deploy via SFTP
      env:
        SFTP_HOST: ${{ secrets.SFTP_SERVER }}
        SFTP_USER: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        lftp -e "set sftp:auto-confirm yes; mirror -R ./ /; quit" -u $SFTP_USER,$SFTP_PASSWORD sftp://$SFTP_HOST

